theme = "catppuccin_macchiato"

[editor]
line-number = 'relative'
bufferline = 'multiple'

[keys.normal]
"C-d" = ["page_cursor_half_down", "align_view_center"]
"C-u" = ["page_cursor_half_up"]

"A-h" = ["jump_view_left"]
"A-j" = ["jump_view_down"]
"A-k" = ["jump_view_up"]
"A-l" = ["jump_view_right"]

"H" = [":buffer-previous"]
"L" = [":buffer-next"]
